Squashed 'social/' changes from 88747d0cfb..3b7cc592c5
3b7cc592c5 Update translation files
12388ecd75 [BOT] post-merge updates
ef46b47103 [UPD] Update mail_tracking_mass_mailing.pot
930d3971fc Merge PR #1412 into 17.0
495a983101 Translated using Weblate (Italian)
ab8c4c43ce Translated using Weblate (Italian)
577b1dee2e [MIG] mail_tracking_mass_mailing: Migration to 17.0
8a9d65eda9 [IMP] mail_tracking_mass_mailing: pre-commit auto fixes
95bd61c7dc Translated using Weblate (Italian)
85453b7381 Translated using Weblate (Italian)
820048bc07 Translated using Weblate (Italian)
e199b9e55f Translated using Weblate (Italian)
27f38091da Added translation using Weblate (Italian)
a4850bb801 Update translation files
b67ea681a3 Update translation files
ddbbbb1b0d Update translation files
5eb25e32fe Update translation files
a6b3fc9ab6 Update translation files
5c2fa82d90 Update translation files
97d8b7ae01 Update translation files
36fc858ce7 Update translation files
2a367ef589 Update translation files
31f6041c09 Update translation files
b2fbe7b862 Translated using Weblate (French)
5c17dd2ba2 Translated using Weblate (Italian)
babbd4e9da Translated using Weblate (Spanish)
b9b00e3603 [MIG] mail_tracking_mass_mailing: finish migration to 16.0
4014e2b324 [MIG] mail_tracking_mass_mailing: Migration to 16.0
7d3e6c0aab [MIG] mail_tracking_mass_mailing: Migration to v15.0
6d4721afe8 mail_tracking_mass_mailing: Set traces in error according to tracking
2735315c5b [MIG] mail_tracking_mass_mailing: Migration to v14.0
1c27abd15b [IMP] pre-commit run -a
1e79a33e33 [MIG] mail_tracking_mass_mailing: Migration to 13.0
07114f2600 [IMP] mail_tracking_mass_mailing: black, isort, prettier
b37ecf1332 [MIG] mail_tracking_mass_mailing: Migration to 12.0
29630f4496 [MIG] mail_tracking_mass_mailing: Migration to 11.0
7815746e91 [FIX] mail_tracking_mass_mailing: Integration tests (#258)
1f6f64b4b6 [10.0] mail_tracking_mass_mailing: Migration to 10.0
cec74fd79b mail_tracking_mass_mailing module
e7548c9f5b mail_tracking_mass_mailing (#78)
2d458df82a [BOT] post-merge updates
a5e52d8606 [UPD] Update mail_tracking.pot
fe541915ff Merge PR #1367 into 17.0
e981f3cc6d [MIG] mail_tracking: Migration to 17.0
549006c5dc [IMP] mail_tracking: pre-commit auto fixes
b293ba54de [FIX] mail_tracking: be closer to what Odoo does in a nodb environment
b5fa4255fc [IMP] mail_tracking: Give example that actually works in readme
c4addf4028 Translated using Weblate (French)
0f139e608d Translated using Weblate (Italian)
0c71ca5a52 Translated using Weblate (Portuguese (Brazil))
ab323e561a [16.0][FIX] mail_tracking debug mode error
175aadff66 Translated using Weblate (Italian)
c8e5ae90fc [FIX] mail_tracking: validated mailbox when computing isInFailedDiscuss
41ccc411f9 Translated using Weblate (Spanish)
f25a4a31e6 [MIG] mail_tracking: Completed migration to 16.0
e0fee46fa9 [MIG] mail_tracking: Migration to 16.0
0de49f2acd [FIX] mail_tracking: failed messages in thread
2fe46dd8e1 [IMP] mail_tracking: New config parameter to disable the tracking image
aea5fa7548 [FIX] mail_tracking: allowed trackings compute
e0a4c5b1fe [FIX] mail_tracking: thread permissions
4d6d8cbb17 Fix mail tracking bounce notification not logged
1260333caf Translated using Weblate (Italian)
c43890993b Update translation files
aed012d07f [UPD] Update mail_tracking.pot
89e10b9310 [FIX] mail_tracking: Crash to add malformed emails to recipients suggestions
4912eb5389 use keyword arguments in build_email to comply with portal tests
f9aa7c1fd4 [FIX] mail_tracking: js linter warnings
8301727ee1 [IMP] mail_tracking: remove legacy hooks
4cc3d4dc32 [FIX] mail_tracking: permissions
b760f0780e [FIX] mail_tracking: error when filtering by "Sent"
2e2158594c [FIX] mail_tracking: process sent events
84535f3629 [IMP] mail_tracking_mailgun: mass mailing manual tracking
38d233e9ff [FIX] mail_tracking: mixed classes
5e9998e324 [MIG] mail_tracking: Migration to 15.0
5c383b4724 [IMP] mail_tracking: black, isort, prettier
773ba68bf6 [FIX] mail_tracking: change order of inheritance and use return
4e20cb65aa [FIX] mail_tracking: use recipient_address to search emails
baa05ca8ab [PORT] porting js code to comply with OWL
b8600c8cb5 [FIX] Change operator to 'ilike'
2505952391 [FIX] mail_tracking: Added restriction on email search.
266d8cff75 [FIX] mail_tracking: reduce spammy score
452872d611 [FIX] mail_tracking: Modification in unitest.
b62aadeea8 [14.0][MIG] mail_tracking
bb40ec162c [MIG] mail_tracking: Migration to 14.0
560d49cc42 [IMP] mail_tracking: black, isort, prettier
dd9bced5ef [FIX] mail_tracking: Store cc
1cedb804a4 [IMP] mail_tracking: Discuss failed messages: Button and domain + Only show confirmation if needed
feb6c1c9a2 [IMP] Apply pre-commit changes: Resolve conflicts
41824cf401 [FIX] mail_tracking When a user try to resend message gets an error stating that it's only allowed for users who belong to the Administration/Settings group
d90620f135 [FIX] re.search will return None when nothing found. So we have to check for this
29edda30bc [IMP] mail_tracking: Ignore catchall
5b34971637 [IMP] mail_tracking: Test 'to' and named emails
aa8e1e6481 [IMP] mail_tracking: Store To recipients and omit aliases
12e3347b08 [FIX] mail_tracking: do not warn not found if already opened
b52322594c [FIX] mail_tracking: Changed injection method for 'failed_message_ids' field
c3d54d0784 [MIG] mail_tracking: Migration to 13.0
3b77c528f9 [IMP] mail_tracking: black, isort
f7c8acf6bb [FIX] mail_tracking: Refresh thread widget when sets a message as reviewed
b5ee63dec6 [IMP] mail_tracking: Failed Messages to 12.0
b9e43d6d8e [IMP] mail_tracking: translations
17c39f63ae [IMP] mail_tracking: Convert 'partner_trackings' to dict
56130736da [IMP] mail_tracking: Cc name & check if mail is Cc
2d0c3b7633 [IMP] mail_tracking: mail.thread filter for tracking errors
50a4efbf68 Translated using Weblate (Spanish)
56a0e70b1b [FIX] mail_tracking: Show correctly blank image
d409b23ad0 [IMP] mail_tracking: Adapt test to set (not order preserved)
1756ce1498 [FIX] mail_tracking: Repeated suggested cc emails
46f5cc44ed [FIX] Bug {TypeError: dict.message.hasEmailCc is not a function} during the creation of a new document.
26e8063fd2 [MIG] mail_tracking: Adapt Cc to 12.0
ca30aa43bb [IMP] mail_tracking: Cc
8447b7ff33 [FIX] mail_tracking: Don't call write inside other write
8ab506bed7 [MIG] mail_tracking: Migration to 12.0
6b84874a1a Translated using Weblate (Catalan)
d5c757c00c [IMP] mail_tracking: Put button box at the end of the view
bf03db317d Fix README.rst images not visible in GitHub and Odoo
64dd01b7e9 [IMP] mail_tracking: email score performance (#299)
455decbeb6 Translated using Weblate (French) [ci skip]
0fd3693074 [MIG] mail_tracking: Migration to 11.0
53ec4fe4b6 [FIX] mail_tracking js could break other modules using chat_manager
3dd37c628d IMP mail_tracking performances
434d4b7439 [FIX] mail_tracking: bugfixes (#199)
e413b11cf1 [9.0][IMP] mail_tracking: Improve view with error details
62647ebc08 [IMP] Shut mock exceptions up
cd3302f7da [FIX] mail_tracking: Obtain outgoing server with sudo
ef032736b0 [FIX][9.0] partner buttons view on enterprise
ad25c28ae0 [FIX] Sender label is repeated in search fields
b3fc8bd769 [9.0][FIX][mail_tracking] Control exception when mail_message was removed (#132)
a800927d66 [8.0][FIX][mail_tracking] Use event recipient address to find partners and contacts to bounce (#133)
bb5432c095 Add access to portal/public user to his own email trackings
e0f73c77d9 [IMP] mail_tracking: Allow to define a custom mail_tracking base url
d607b97fdb [IMP] mail_tracking performance and bounce process (#103)
ae82c2790e [MIG] mail_tracking: Migrated to 10.0
7d65c792af [MIG] Make modules uninstallable
741e6a98b5 [FIX] mail_tracking: Typo
80e3341234 [MIG] mail_tracking
e232d6c4d3 [FIX] Update email_score when email changes
5c5ea35247 [8.0][IMP][mail_tracking] Speed installation time and discard concurrent events (#82)
dcf1274ca1 [8.0][ADD] mail_tracking addon (#67)
bd23e6adbf Merge pull request #1378 from Tecnativa/17.0-update-copier
07a7f5de76 [UPD] Update copier to v1.22

git-subtree-dir: social
git-subtree-split: 3b7cc592c5dc5ec25a674172f2219d7834f3a676