Squashed 'server-auth/' changes from 58993c76e3..68a5523423
68a5523423 [BOT] post-merge updates
3f4e0b7191 Merge PR #736 into 17.0
7fe6b8a768 Update translation files
f5a8de069c [BOT] post-merge updates
1626db69e5 [UPD] Update auth_oauth_multi_token.pot
b415d6c487 Merge PR #742 into 17.0
7abc6d4060 [MIG] auth_oauth_multi_token: Migration to 17.0
58e6779cb0 [IMP] auth_oauth_multi_token: pre-commit auto fixes
6f91bc0a0a Added translation using Weblate (Italian)
24ddc93ce8 [BOT] post-merge updates
6b1eb73797 [BOT] post-merge updates
c0b28ee717 Merge PR #726 into 17.0
f409b7d669 Update translation files
9c5c3baf38 [BOT] post-merge updates
39d661f482 [UPD] Update users_ldap_populate.pot
617a4d2ef7 Merge PR #675 into 17.0
2d247050fb [IMP] update dotfiles
5b078f1369 [IMP] auth_saml: only write value that changes
5f572c89fe Update translation files
0a15badf3f [BOT] post-merge updates
42cf02622d [UPD] Update auth_jwt.pot
13d21c6151 Merge PR #751 into 17.0
559b3fee2a [MIG] auth_jwt: Migration to 17.0
58560391a3 Translated using Weblate (Italian)
290f8c1f9b Translated using Weblate (Italian)
d5135a4342 Translated using Weblate (Italian)
516540774f Added translation using Weblate (Italian)
80cd757599 [UPD] README.rst
6c6a6fb614 Translated using Weblate (Spanish)
b3db3c40cc Added translation using Weblate (Spanish)
b2001adc93 auth_jwt 16.0.1.1.0
9942618bb2 [UPD] README.rst
6131bfff7a [UPD] Update auth_jwt.pot
e003ebd722 [IMP] auth_jwt: check cookie_name is present in cookie mode
8aeef4a989 [FIX] auth_jwt: don't use public mode if a cookie is present
2353a46bb5 [IMP] auth_jwt: refactor
91333a6e8a auth_jwt: minor refactoring
621b4908d2 auth_jwt: clarify exceptions
d8017fb3c4 auth_jwt: add cookie mode
7c33f97735 [UPD] README.rst
9a78860cb8 [UPD] Update auth_jwt.pot
cda5566840 [MIG] auth_jwt: convert unit tests to integration tests
e884ba22a0 [MIG] auth_jwt from 14 to 16
e82d36fb59 auth_jwt 14.0.2.0.0
f486b8a298 [UPD] Update auth_jwt.pot
6b17cc6747 [IMP] auth_jwt: Add validator.next_validator_id to allow validator chaining
d00e0a7528 auth_jwt 14.0.1.2.0
e8c12c3993 auth_jwt: Relicence under LGPL
8dd53c6b01 auth_jwt 14.0.1.1.0
51365a8db5 [UPD] README.rst
3c074d6e50 [IMP] auth_jwt: add public_or_jwt auth method
b430a28c0e auth_jwt 14.0.1.0.1
6bc609b27d [UPD] README.rst
2d167fdc0c [UPD] Update auth_jwt.pot
e6c93e2aae [MIG] auth_jwt
030164bd56 Rename auth_jwt_test to auth_jwt_demo
16bc96b3db auth_jwt: more precise precondition check
89dd810f80 auth_jwt: mock instead of committing in tests
05a10d5d16 auth_jwt: fix jwks URI support
06897a4466 auth_jwt: docs clarification and fixes
40aedcca5f auth_jwt: add nbf validation test
910a716044 auth_jwt: support multiple audiences
22e8c80637 auth_jwt: add signature algorithms
da4dfd00c2 auth_jwt: use PyJWT instead of python-jose
a0ca0a0412 [ADD] auth_jwt
bfd34e0904 [BOT] post-merge updates
e29d7d0f74 [UPD] Update auth_ldaps.pot
1bdc7dbfd9 Merge PR #643 into 17.0
bcb339210f [FIX] Pre-migrate script
023ac25e9f [MIG] users_ldap_populate: Migrate to 17.0
8f23700032 [IMP] users_ldap_populate: pre-commit auto fixes
1ea3f06d18 Translated using Weblate (Portuguese (Brazil))
366e89581a Translated using Weblate (Italian)
cba59df61c [MIG] users_ldap_populate: Migration to 16.0
b2938df5d9 [MIG] users_ldap_populate: Migration to 14.0
2ab73b6b69 [IMP] users_ldap_populate: black, isort, prettier
3bb7c70dfa Apply dotfiles
bf564d0a00 [MIG] users_ldap_populate: Migration to 13.0
96f49f25a7 [IMP] users_ldap_populate: black, isort, prettier
913b0e30b8 [FIX] users_ldap_populate: Fix POT + es
7b8a363e09 [FIX] users_ldap_populate: use str, not bytes
50d479cfc1 [IMP] users_ldap_populate: Cherry-pick from hbrunn
3e7790e0ed [MIG] users_ldap_populate: Migration to 12.0
fb93f2252d [10.0] [FIX] users_ldap_populate special characters (#1564)
9018d6661d Translated using Weblate (French)
82484468d7 [FIX] auth_ldap_populate
70b6d652ff [FIX] strange behavior of users_ldap_populate
77de59144f [FIX] users_ldap_populate. No unneeded password reset message.
e5158c8789 remove obsolete .pot files [ci skip]
836a88d0f0 [FIX] users_ldap_populate. Wrong field name in test.
24713ba36c users_ldap_populate: try/except on import ldap
be214b449f [MIG] users_ldap_populate port v8 feature
7afa7ea643 [ADD] users_ldap_populate: migrate functionality added to 6.1 after 7.0 port (#408)
f9d2e03d94 10.0 migrate users_ldap_populate (#657)
bd4b5648cb [MIG] Rename manifest files
454b53dee0 [MIG] Make modules uninstallable
dc9064bee2 [FIX] remove en.po that was erroneously created by transbot
884a25b9a4 update french translation
78392531e1 updated i18n files
b6d40c0d35 9.0 users_ldap_populate fix 2 bugs
6a682d7493 Reset version 9.0.1.0.0
ec980960ff Fix 9.0 version number
c78a8e4b4c port user_ldap_populate to new API
702b25233a Port the ldap_populate in V9
4c834810b7 [MIG] Make modules uninstallable
948cee2f75 [UPD] prefix versions with 8.0
6440e56de1 [FIX] users_ldap_populate: Protect ldap library import
1ed25dde7e Add missing default oca icons
2a164a5a89 Add OCA as author of OCA addons
c5155db66e Add license key in __openerp__.py
65cb66e4eb [FIX] travis
c4762c7c88 [FIX] pylint
05a8578928 Port users_ldap_populate to v8
7c288480db Move users_ldap_populate out of unported
c6c6b41fa5 move all modules to __unported__ on master branch and set installable=False
91725fef49 Generate .pot files
9dc1a0f641 FIX version numbers; view type is deprecated
ffe4368aab Therp's modules to sync OpenERP with LDAP directories
def9106480 [BOT] post-merge updates
e9d0014d21 [UPD] Update auth_session_timeout.pot
e58c14135f Merge PR #646 into 17.0
91aa977075 Translated using Weblate (Italian)
1273c213f2 Update translation files
e1aa47926d [BOT] post-merge updates
295333c835 [UPD] Update auth_oidc.pot
93a97b88b8 Merge PR #706 into 17.0
ba7dc4a8ad [BOT] post-merge updates
4aef25fece Merge PR #686 into 17.0
a162ae9394 [BOT] post-merge updates
f11d355167 Merge PR #709 into 17.0
55330d391e [UDP] auth_api_key: Update description for reason to keep this module
4f824b072f Translated using Weblate (Italian)
1abba79d4e Update translation files
d303261d39 [BOT] post-merge updates
254815258e [UPD] Update auth_api_key.pot
da741f060f Merge PR #700 into 17.0
cf071cebad [IMP] auth_oidc: prompt for account on AAD login
10be257938 [BOT] post-merge updates
0ad9f1d2ac Merge PR #704 into 17.0
5519ea2693 auth_api_key: add option to auto archive key with user
cc5c249d40 auth_api_key: archive key when user is archived
2d605f471c auth_api_key_group: fix author name
fecda7c1e3 auth_api_key_group: dev status -> Beta
f4b9811702 [14.0] auth_api_key: allow to update api key from form view and hide keys in UI
cb373c86bf [ADD] auth_session_timeout:Added pre-migration script for inactive_session_time_out_ignored_url.
e3d02aa721 Translated using Weblate (Finnish)
0cef202d23 Added translation using Weblate (Finnish)
72a34836af [MIG] auth_oauth_multi_token: Migration to 16.0
e96e649cc3 [MIG] auth_oauth_multi_token: Migration to v15.0
bf4fbf53f2 [MIG] auth_oauth_multi_token: Migration to v14.0
38a7fcdc61 [IMP] auth_oauth_multi_token: preserve _oauth_clear_token method
dea37c07b3 auth_oauth_multi_token: add contributor
11781167a6 auth_oauth_multi_token: reset main token on clear
75dc3ee6d6 auth_oauth_multi_token: cascade delete tokens
871efe0dd0 auth_oauth_multi_token: index
1fbde6d6b0 [MIG] auth_oauth_multi_token: v13
991083a1de [IMP] auth_oauth_multi_token: black, isort, prettier
02b824487b [MIG] auth_oauth_multi_token: Migration to 12.0
efc918febf [MIG][11.0] auth_oauth_multi_token
40f76b443c [MIG+IMP][10.0] auth_oauth_multi_token
f456687f49 [add] auth_oauth_multi_token
acc289544b [FIX] impersonate_login: fix user_id comodel_name
0beb977d0e [BOT] post-merge updates
3a7e6e0cc5 [UPD] Update impersonate_login.pot
099a6bb208 Merge PR #684 into 17.0
4ec4340a59 Translated using Weblate (Italian)
9b0ddbd0ff Translated using Weblate (Italian)
1c35f21546 Added translation using Weblate (Italian)
4dfb296ce9 Added translation using Weblate (Italian)
30ffc9a2e1 [FIX] impersonate_login: fix computed body field + add inverse
62bb103097 [BOT] post-merge updates
4e3e5aba07 [UPD] Update impersonate_login.pot
328fae61d2 Merge PR #680 into 17.0
b01d34199a [BOT] post-merge updates
78becfe093 [UPD] Update auth_admin_passkey_totp_mail_enforce.pot
acdacb2a2a Merge PR #625 into 17.0
91ac7ba69b [MIG] impersonate_login: migration to V17
838cf65a6b Translated using Weblate (Italian)
57cc50c4e9 Update translation files
e23a843dc0 [BOT] post-merge updates
aac78a8458 [UPD] Update auth_signup_verify_email.pot
a5174dd132 Merge PR #681 into 17.0
f426dfe143 [MIG] auth_signup_verify_email: Migration to 17.0
f5f5af4370 [IMP] auth_signup_verify_email: pre-commit execution
707978c811 Translated using Weblate (Spanish)
0ee50ce020 [MIG] auth_signup_verify_email: Migration to 16.0
cd061cd213 [IMP] auth_signup_verify_email: pre-commit stuff
7f41cfe2df [MIG] auth_signup_verify_email: Migration to 15.0
3220edd142 [FIX] auth_signup_verify_email: Use real email address for tests
4c0cb254f0 [MIG] auth_signup_verify_email: Migration to 14.0
ad914f71be [IMP] auth_signup_verify_email: black, isort, prettier
7506b25fd8 Added translation using Weblate (Arabic)
657631f7a9 [MIG] auth_signup_verify_email: Migration to 13.0
13590617cc [IMP] auth_signup_verify_email: black, isort, prettier
ce5e4a52bc [FIX] auth_signup_verify_email: make tests compatible with website
4a0fab3f94 [IMP] auth_signup_verify_email: Remove hack
a71dde5b18 Translated using Weblate (Croatian)
5311710e1a Translated using Weblate (Portuguese (Brazil))
f5b3ebea34 [MIG] auth_signup_verify_email: Migration to 12.0
4e9feb2b54 [FIX] auth_signup_verify_email: Improve signup error messages
1a884c48b5 [FIX+REF] auth_signup_verify_email: Fix tests + Skip mail send in tests and use email_validator (#29)
b0cc9922c9 [MIG][11] auth_signup_verify_email
a0055aea34 OCA Transbot updated translations from Transifex
ba81423a95 [MIG][10] auth_signup_verify_email
c9c7d5b13a [9.0][MIG][auth_signup_verify_email] Migration. (#436)
aa78cdd2af [MIG] impersonate_login: pre-commit
71c5b22e81 [14.0][ADD] impersonate_login
8d209e9ef2 Update translation files
3deb9973d0 [BOT] post-merge updates
8069448555 [UPD] Update auth_saml.pot
71f49b29dc Merge PR #634 into 17.0
07f503cc7f [ADD] auth_admin_passkey_totp_mail_enforce
3a36b71865 Translated using Weblate (Italian)
98e9cd82a2 [MIG] Improved test coverege
fcdd36edec [FIX] Remove pandoc
1337793be8 [IMP] auth_ldaps: Allow disabling LDAP ref-chasing
4710036f71 [FIX] Remove model description
d2ab2c3911 [MIG] auth_ldaps: Migration to 17.0
77e2911edb Update translation files
e619ce9ceb [BOT] post-merge updates
9d52d53b73 [UPD] Update auth_api_key_group.pot
21507a8057 Merge PR #654 into 17.0
440b7872d5 [IMP] auth_saml: Allow admin/managers to edit User SAML information
f5aa0d4c3f [FIX] auth_saml: update signin method
306979ebf5 [MIG] auth_saml: migrate to V17
70aed43a3d [MIG] auth_saml: pre-commit
d1c36b4cb0 [BOT] post-merge updates
d410ac1b44 FIX auth_saml: password reset when deactivating the config settings
078340c06b Added translation using Weblate (Italian)
4379dc28d4 [BOT] post-merge updates
ec0014675e Small bugfix, RelayState can be empty
281955abd3 Update translation files
65a6d70247 [UPD] README.rst
eeb799e484 Added translation using Weblate (Spanish)
b6756fd14c auth_saml 16.0.1.0.2
f5781c3ff0 [UPD] README.rst
b772aa5462 auth_saml: add maintainer
5e65e77a7d auth_saml 16.0.1.0.1
2c7734161f [FIX]auth_saml: fix singleton error.
5e13156324 Update translation files
8272bb2b68 [UPD] README.rst
a360bd35a6 [UPD] Update auth_saml.pot
a0c6b6e679 [MIG] auth_saml: Migration to 16.0
4b96fc01e0 [ADD] auth_saml: handle redirect parameter in the URI
1f98ba93e1 [ADD] auth_saml: Improve login page
9e3c20be34 auth_saml 15.0.1.1.1
51a25cf3b2 Place upper bound in cryptography indirect dependency
9f50887080 Translated using Weblate (French)
84bcd0fb5e Update translation files
e86ed822d2 auth_saml 15.0.1.1.0
fa19fcaafa [UPD] README.rst
e9a9b3bd97 [UPD] Update auth_saml.pot
f8766da34e 🚑 Fix the module by adding a transaction to commit the token 🚑 Fix the disallow password for users with SAML ids Added tests to ensure the feature works correctly. Admin user is also an exception from not having a password. In Odoo 15.0, this is the standard user to connect for administrative task, not the super user. ✨ Improve provider form and list views ✨⏩ port of 11.0 automatic redirection from 11.0 version. Use disable_autoredirect as a parameter query to disable automatic redirection (for example https://example.com/web/login?disable_autoredirect=) 💄 Add certificate file name fields to improve the UI 📝 Add required on several fields of the SAML provider; without them the server will crash and there is not enough information to make SAML work. ✨ Split signing to have finer control and be compatible with more IDP. 🔨 Integrate token into res.users.saml, removing auth_saml.token. No need for a separate table, and no more need to create lines in the table. 📝 Avoid server errors when user try metadata page without necessary parameters. 🚑 Replace method call from odoo.http.redirect_with_hash to request.redirect as the former does not exists in Odoo 15.0 anymore. 📚 Improved the module documentation 👕 pylint fixes and other fixes or minor changes
44aab46938 Translated using Weblate (French)
e412c38991 [UPD] Update auth_saml.pot
80fefa06ef [MIG] auth_saml: Migration to 15.0
77ee0ae909 [IMP] auth_saml: black, isort, prettier
95b8332399 auth_saml 14.0.1.0.1
8293ae4d57 auth_saml: declare debian dependency
e0cf8c40e6 [MIG] auth_saml: Migration to 14.0
478527c1cb [IMP] auth_saml: black, isort, prettier
39f183cad0 auth_saml 12.0.1.0.1
ee21b40c98 Update translation files
1367c10ca2 [UPD] Update auth_saml.pot
14afa11352 FIX auth_saml committing saml_access_token otherwise login_and_redirect uses old data
eae5c56bfa [UPD] README.rst
a88940bdbe [MIG][REF] General cleanup for migration
706e2a1bd3 [MIG] auth_saml to 12.0
f27c5ec899 [FIX] dependencies
772784ab4f Update translation files
58f6e98810 [UPD] Update auth_saml.pot
95c0aee5aa [FIX] auth_saml: Fix KeyError using auth_oauth module. (#149)
32fcb00295 [FIX] auth_saml: Remove broken symlink
4e12101056 [ADD] icon.png
7e43593b17 [UPD] Update auth_saml.pot
3b3c30c94b Typo
092fea84f5 [MIG] auth_saml: Migration to 11.0
aedb350d7f [IMP] Move files in a subdirectory
dcdf86eafa [MIG] auth_api_key_group: Migration to 17.0
4f5a5d3663 [IMP] auth_api_key_group: pre-commit auto fixes
4bc3e02280 Translated using Weblate (Italian)
c9364dcaad Added translation using Weblate (Italian)
e26e08c1fe [BOT] post-merge updates
78b110a1e7 [16.0][MIG] - auth_api_key_group
7feb51981d [MIG] auth_api_key_group: Migration to 15.0
8d753a9336 Add auth_api_key_group
5e04c9cb47 [17.0][IMP] auth_session_timeout: user websocket instead of longpolling
495241af1e [MIG] auth_session_timeout: Migration to 17.0
2bb2d4b918 [IMP] auth_session_timeout: pre-commit auto fixes
64bcac2d16 Translated using Weblate (Catalan)
938bb09419 Translated using Weblate (Italian)
a297521f10 Translated using Weblate (Spanish)
232cd50464 Update translation files
da5e6631b4 Translated using Weblate (Spanish)
37c820e689 Update translation files
5173855b77 [BOT] post-merge updates
fb540d5dc0 [UPD] Update auth_session_timeout.pot
540390f5f4 [FIX] auth_session_timeout: problem whereby page is refreshed with F5, but /web is a public route, so it does not trigger the session check but it does trigger session save, so the file mtime is updated before the second HTTP call makes the check takes place, and session is not expired
4c6270d060 [13.0][IMP] timeout check triggered on session uid
b7d71da79e [MIG] auth_session_timeout: Migration to 16.0
017acec16d Translated using Weblate (Italian)
768fdb3064 Translated using Weblate (Italian)
52aacb6f63 Translated using Weblate (Catalan)
1a075d9651 [MIG] auth_session_timeout: Migration to 15.0
cba782d1cf [IMP] auth_session_timeout: black, isort
dfadf06447 Translated using Weblate (Portuguese (Brazil))
86a0c7a559 auth_session_timeout 14.0.1.0.1
83b1477a47 [FIX] auth_session_timeout: session timeout applies only to user
3081588824 [MIG] auth_session_timeout: Migration to 14.0
efa246b2aa Update translation files
9970dce83b Update translation files
53ed9f8e45 [REF] pre-commit lint
a963a14c5d [MIG] auth_session_timeout: Migration to 13.0
b9bbc410e1 Translated using Weblate (Portuguese (Brazil))
5cf72ec50a [12.0][MIG] auth_session_timeout
cf8041dbc5 [MIG] auth_session_timeout: Migration to version 11.0
4b3e9237ca auth_session_timeout: Migration to 11.0
9bed7d3ec8 corrects AttributeError: 'HttpRequest' object has no attribute 'http' (#1070)
35465eb8a1 auth_session_timeout: Deprecate backwards compat + improve * Deprecate backwards compatibility methods that were retained during v9 rework * Upgrade API and rename a few things for PEP-8 * Switch to HttpCase for tests * Switch to isolated build
01094a729b Module auth_session_timeout: Pluggability (#887)
04d76b7d9c auth_session_timeout: Migrate to v10 * Bump versions * Installable to True * Add Usage section to ReadMe w/ Runbot link * `_crypt_context` now directly exposes the `CryptContext` * Change all instances of openerp to odoo * Add test coverage to IrConfigParameter * Add test coverage for res.users * Remove db from `get_session_parameters` method call * Remove deprecated skiparg for ormcache * Fix tests & lint * Switch cache to use self.cr.dbname * Fix ormcache
bbb793c657 Rename manifest files
bd23d0703c Make modules uninstallable
b67b4d0057 auth_session_timeout: References to old name
105309a40a inactive_session_timeout > auth_session_timeout
1aacc37304 [IMP] auth_ldaps: pre-commit stuff
d416e849be [UPD] README.rst
9df95fac82 [UPD] README.rst
ffa291b456 [UPD] Update auth_ldaps.pot
75741abe48 [16.0][MIG] auth_ldaps: Migration to 16.0
5ffaa85434 Update translation files
0a5e60442f [UPD] README.rst
39ad4508dc Update readme with oca-gen-addon-readme
92ed5fc2d5 [MIG] auth_ldaps: Migration to 15.0
bea6d383b2 [IMP] auth_ldaps: black, isort, prettier
1a6c3f1133 auth_ldaps 14.0.1.0.1
3a82e6cc51 [FIX] fix ldaps certificate verification
5fea19d1b5 Translated using Weblate (Italian)
c3526ec8a3 Translated using Weblate (Italian)
92cca4c58b Added translation using Weblate (Italian)
059fdda45c [UPD] README.rst
c4fafb884d [UPD] Update auth_ldaps.pot
5d9b67a9fa [MIG][14.0] auth_ldaps
89d89d9966 auth_ldaps 13.0.1.0.1
87cf16eca9 [UPD] README.rst
0b82f939c6 [UPD] Brainbean Apps => CorporateHub
92a72298d9 [UPD] README.rst
f7c7d2ae5d [UPD] Update auth_ldaps.pot
272f5aa68c add python-ldap dependency
a81890c426 fix linting
28d819d9a9 [13.0][MIG] auth_ldaps
45c56e90a6 [IMP] auth_ldaps: black, isort, prettier
90c9ea872e [12.0][FIX] auth_ldap_attribute_sync & auth_ldaps: author name
7a0fc344cd [FIX] auth_ldaps: Specify ldap as Python dependency and safely import it
d2db33d387 [MIG] auth_ldaps: Migration to 12.0
f8a0dfd706 [ADD] auth_ldaps
f138da23c7 Check that request.session exists before accessing it
8bd6f788f2 [IMP] option for TOTP/2FA bypass for admin passkey

git-subtree-dir: server-auth
git-subtree-split: 68a5523423f4a6a8163b4079c1d8a8f7a44fed02